In [1]:
# Data management imports
import pandas as pd
import numpy as np
import polars as pl
import polars.selectors as cs

In [2]:
nd = pl.read_parquet('../Data/insects.parquet')

In [3]:
ndp = nd.to_pandas()

In [4]:
ref_data_cols = np.unique(ndp.columns[np.random.randint(0,len(ndp.columns)-1, 100)])

In [5]:
rdc = [str(x) for x in ref_data_cols]

In [6]:
pl.from_pandas(ndp[ref_data_cols])

shape: (259_613, 98)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ domWoodTy ┆ hurs_mean ┆ hurs_mean ┆ hurs_mean ┆ … ┆ tasmin_su ┆ tasmin_su ┆ tasmin_su ┆ tasmin_s │
│ pe_0      ┆ _30d_m11_ ┆ _30d_m3_p ┆ _30d_m4_p ┆   ┆ m_30d_m1_ ┆ m_30d_m2_ ┆ m_30d_m4_ ┆ um_30d_m │
│ ---       ┆ pre1      ┆ re4       ┆ re1       ┆   ┆ pre3      ┆ year0     ┆ year0     ┆ 5_pre3   │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1441      ┆ 87.812296 ┆ 76.055617 ┆ 73.762191 ┆ … ┆ -176.9187 ┆ 43.721785 ┆ 151.25154 ┆ 231.4207 │
│           ┆           ┆           ┆           ┆   ┆ 36        ┆           ┆ 6         ┆ 77       │
│ 1441      ┆ 87.812296 ┆ 76.055617 ┆ 73.762191 ┆ … ┆ -176.9187 ┆ 43.721785 ┆ 151.25154 ┆ 231.4207 │
│           ┆           ┆           ┆           ┆   ┆ 36        ┆           ┆ 6         ┆ 77       │
│ 1441      ┆ 87.812296 ┆ 76.055617 ┆ 73.762191 ┆ … ┆ -176.9187 ┆ 43.721785 ┆ 151.25154 ┆ 231.4207 │
│           ┆           ┆           ┆           ┆   ┆ 36        ┆           ┆ 6         ┆ 77       │
│ 1441      ┆ 87.812296 ┆ 76.055617 ┆ 73.762191 ┆ … ┆ -176.9187 ┆ 43.721785 ┆ 151.25154 ┆ 231.4207 │
│           ┆           ┆           ┆           ┆   ┆ 36        ┆           ┆ 6         ┆ 77       │
│ 1441      ┆ 87.445206 ┆ 76.678424 ┆ 72.005566 ┆ … ┆ 18.674613 ┆ -60.49135 ┆ 91.789006 ┆ 257.8856 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆ 77       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 409       ┆ 86.726532 ┆ 75.034212 ┆ 67.705772 ┆ … ┆ 2.094308  ┆ -36.30214 ┆ 63.428547 ┆ 149.6465 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ 17       │
│ 409       ┆ 86.726532 ┆ 75.034212 ┆ 67.705772 ┆ … ┆ 2.094308  ┆ -36.30214 ┆ 63.428547 ┆ 149.6465 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ 17       │
│ 409       ┆ 86.726532 ┆ 75.034212 ┆ 67.705772 ┆ … ┆ 2.094308  ┆ -36.30214 ┆ 63.428547 ┆ 149.6465 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ 17       │
│ 409       ┆ 86.726532 ┆ 75.034212 ┆ 67.705772 ┆ … ┆ 2.094308  ┆ -36.30214 ┆ 63.428547 ┆ 149.6465 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ 17       │
│ 409       ┆ 86.726532 ┆ 75.034212 ┆ 67.705772 ┆ … ┆ 2.094308  ┆ -36.30214 ┆ 63.428547 ┆ 149.6465 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ 17       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
pl.from_pandas(ndp)[rdc]

shape: (259_613, 98)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ domWoodTy ┆ hurs_mean ┆ hurs_mean ┆ hurs_mean ┆ … ┆ tasmin_su ┆ tasmin_su ┆ tasmin_su ┆ tasmin_s │
│ pe_0      ┆ _30d_m11_ ┆ _30d_m3_p ┆ _30d_m4_p ┆   ┆ m_30d_m1_ ┆ m_30d_m2_ ┆ m_30d_m4_ ┆ um_30d_m │
│ ---       ┆ pre1      ┆ re4       ┆ re1       ┆   ┆ pre3      ┆ year0     ┆ year0     ┆ 5_pre3   │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1441      ┆ 87.812296 ┆ 76.055617 ┆ 73.762191 ┆ … ┆ -176.9187 ┆ 43.721785 ┆ 151.25154 ┆ 231.4207 │
│           ┆           ┆           ┆           ┆   ┆ 36        ┆           ┆ 6         ┆ 77       │
│ 1441      ┆ 87.812296 ┆ 76.055617 ┆ 73.762191 ┆ … ┆ -176.9187 ┆ 43.721785 ┆ 151.25154 ┆ 231.4207 │
│           ┆           ┆           ┆           ┆   ┆ 36        ┆           ┆ 6         ┆ 77       │
│ 1441      ┆ 87.812296 ┆ 76.055617 ┆ 73.762191 ┆ … ┆ -176.9187 ┆ 43.721785 ┆ 151.25154 ┆ 231.4207 │
│           ┆           ┆           ┆           ┆   ┆ 36        ┆           ┆ 6         ┆ 77       │
│ 1441      ┆ 87.812296 ┆ 76.055617 ┆ 73.762191 ┆ … ┆ -176.9187 ┆ 43.721785 ┆ 151.25154 ┆ 231.4207 │
│           ┆           ┆           ┆           ┆   ┆ 36        ┆           ┆ 6         ┆ 77       │
│ 1441      ┆ 87.445206 ┆ 76.678424 ┆ 72.005566 ┆ … ┆ 18.674613 ┆ -60.49135 ┆ 91.789006 ┆ 257.8856 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆ 77       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 409       ┆ 86.726532 ┆ 75.034212 ┆ 67.705772 ┆ … ┆ 2.094308  ┆ -36.30214 ┆ 63.428547 ┆ 149.6465 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ 17       │
│ 409       ┆ 86.726532 ┆ 75.034212 ┆ 67.705772 ┆ … ┆ 2.094308  ┆ -36.30214 ┆ 63.428547 ┆ 149.6465 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ 17       │
│ 409       ┆ 86.726532 ┆ 75.034212 ┆ 67.705772 ┆ … ┆ 2.094308  ┆ -36.30214 ┆ 63.428547 ┆ 149.6465 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ 17       │
│ 409       ┆ 86.726532 ┆ 75.034212 ┆ 67.705772 ┆ … ┆ 2.094308  ┆ -36.30214 ┆ 63.428547 ┆ 149.6465 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ 17       │
│ 409       ┆ 86.726532 ┆ 75.034212 ┆ 67.705772 ┆ … ┆ 2.094308  ┆ -36.30214 ┆ 63.428547 ┆ 149.6465 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ 17       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘